### ISSUE TITLE
大佬有研究过将cups编译成动态库移植到Android上？

### ISSUE THREAD

**Issue by Swordce** [jianglei12138/cups#1]

**Comment by jianglei12138** [comment]
大学毕业时候的项目，当时确实可以在android上运行。

**Comment by Swordce** [comment]
是否有将cups编译成动态库？我现在是想将cups编译成动态库，然后安卓通过JNI去调用

**Comment by jianglei12138** [comment]
没记错的话应该在编译完成后会生成几个可执行文件和动态库，其中有个叫cupsd。直接adb shell运行cupsd， 然后就可以通过编译出来的动态库开发，动态库与可执行文件他们之间通过socket通信
