### ISSUE TITLE
ubuntu 16.04编译报错avahi_client头文件找不到

### ISSUE THREAD

**Issue by zh163** [jianglei12138/cups#2]
<pre>
$make
Using ARCHFLAGS=
Using ALL_CFLAGS=-Ifontembed -I.. -D_CUPS_SOURCE   -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_THREAD_SAFE -D_REENTRANT  
Using ALL_CXXFLAGS=-Ioprs -Iopvp -I../opvp -I../.. -I.. -D_CUPS_SOURCE   -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_THREAD_SAFE -D_REENTRANT  
Using CC=arm-linux-androideabi-clang
Using CXX=arm-linux-androideabi-clang
Using DSOFLAGS=-L../cups  -Wl,-soname,all -shared -Wall -Wno-format-y2k -Wunused -fPIC -Os -g -fstack-protector -Wno-unused-result -Wsign-conversion -Wno-tautological-compare -D_GNU_SOURCE
Using LDFLAGS=-L../cgi-bin -L../cups -L../filter -L../ppdc -L../scheduler -fPIE -pie -Wall -Wno-format-y2k -Wunused -fPIC -Os -g -fstack-protector -Wno-unused-result -Wsign-conversion -Wno-tautological-compare -D_GNU_SOURCE
Using LIBS=-lcups  -lavahi-client -lavahi-core -lavahi-common -lz -pthread -lm  -lz -llocale
Making all in cups...
Compiling adminutil.c...
Compiling array.c...
Compiling attr.c...
Compiling auth.c...
Compiling backchannel.c...
Compiling backend.c...
Compiling conflicts.c...
Compiling custom.c...
Compiling debug.c...
Compiling dest.c...
dest.c:38:12: fatal error: 'avahi-client/client.h' file not found
#  include <avahi-client/client.h>
           ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [dest.o] Error 1
make: *** [all] Error 1
</pre>

**Comment by jianglei12138** [comment]
删掉config.h中
#define HAVE_AVAHI 1

以及Makedefs文件DNSSDLIBS中的
-lavahi-client -lavahi-core -lavahi-common

**Comment by jianglei12138** [comment]
或者如果想要使用avachi的话，可以事先编译好avahi，把对应的头文件复制到arm-linux-androideabi/sysroot/usr/include

**Comment by zh163** [comment]
好的，感谢您及时回复!
另外，您是否有编译过avahi?
<pre>
if you want to enable avahi, you can put avahi header and library into toolchain sysroot. And 
libavahi-common,libavahi-core,libavahi-client for android could be found in my resposity.
</pre>

**Comment by jianglei12138** [comment]
貌似不能用最新的NDK, 最新的移除了armeabi的支持    https://github.com/jianglei12138/avahi

**Comment by zh163** [comment]
非常感谢！
