### ISSUE TITLE
能否提供联系方式？

### ISSUE THREAD

**Issue by jschyz** [jianglei12138/cups#3]

**Comment by jianglei12138** [comment]
注意查看邮件

**Comment by jschyz** [comment]
![image](https://user-images.githubusercontent.com/3281438/38125998-37b2e31c-3420-11e8-84bb-dda588c3ad45.png)

我用NDK编译新版 Cups ，报 avahi-client 未找到，但是我 apt-get install libavahi-client-dev 包了，求教！

**Comment by jianglei12138** [comment]
交叉编译工具在不指定头文件路径的情况下默认只会从对应交叉工具链中的sysroot/usr/include中查找头文件。 在宿主OS上安装是不会起任何作用的，你需要把对应的头文件复制到sysroot/usr/include中，或者手动指定头文件路径，并且，ubuntu上中存在的avahi动态库是不能在android上运行的。需要交叉编译。

**Comment by jschyz** [comment]
谢谢指教，我把编译好的代码拷贝到板子上后，就奇怪运行不起来了
 
```
1|root@firefly:/ # /etc/pam.d/cups
/etc/pam.d/cups[1]: auth: not found
/etc/pam.d/cups[2]: account: not found
```

**Comment by jianglei12138** [comment]
你有尝试过直接使用cupsd能否正常启动不？

**Comment by jschyz** [comment]
也是跑不起来～ 编个新版到 cups 好困难

**Comment by jianglei12138** [comment]
通过cupsd启动具体什么报错？

**Comment by jschyz** [comment]
无信息，直接越过去了
```
root@firefly:/ # /system/usr/root/sbin/cupsd
2|root@firefly:/ #
```

**Comment by jschyz** [comment]
如果您有空，我愿意有偿付费求帮助！这玩意折腾我好久了 : )

**Comment by jianglei12138** [comment]
有偿就不用了，微信账号发你gmail了，加我一下。有问题微信上说吧

**Comment by liuchenrang** [comment]
你好 有联系方式吗 有问题想请教下
