### ISSUE TITLE
`extern char *setlocale` definition missed

### ISSUE THREAD

**Issue by linkensphere201** [jianglei12138/cups#5]
Hi, 
your liblocale's custom locale.h header file miss the definition of setlocale whose linkage symbol  can be found in sysroot/usr/lib/libc.so by nm

extern char *setlocale(int category, const char *locale); //this line missed

**Comment by jianglei12138** [comment]
you are right, because the locale.h file was aim to build cups successfully, some funtions may not  be defined.
