### ISSUE TITLE
cups编译的时候出现../cups/libcups.so: error: undefined reference to 'nl_langinfo'，请问是哪个库没关联

### ISSUE THREAD

**Issue by yaoyaoujs** [jianglei12138/cups#6]

**Comment by jianglei12138** [comment]
NDK版本对么？ 必须使用r10e的， 之后的版本NDK中移除了很多东西。你这个问题应该是libc
最新版本中 `grep -rn "nl_langinfo"  ./ `

.//sysroot/usr/include/langinfo.h:97:char* nl_langinfo(nl_item __item) __INTRODUCED_IN(26);
.//sysroot/usr/include/langinfo.h:98:char* nl_langinfo_l(nl_item __item, locale_t __l) __INTRODUCED_IN(26);
Binary file .//sysroot/usr/lib/aarch64-linux-android/libc.a matches
Binary file .//sysroot/usr/lib/arm-linux-androideabi/libc.a matches
Binary file .//sysroot/usr/lib/x86_64-linux-android/libc.a matches
Binary file .//sysroot/usr/lib/i686-linux-android/libc.a matches

**Comment by yaoyaoujs** [comment]
谢谢，这个问题已经解决了，换了r10e版本。
