### ISSUE TITLE
后台打开之后，点击增加打印机页面显示notfound

### ISSUE THREAD

**Issue by yaoyaoujs** [jianglei12138/cups#8]
另外移植到android上之后，./cupsd -f 并没有日志输出，但是浏览器中能够打开631页面，但是点击添加打印机全是显示not found,另外发现生成的var/文件夹下面有文件夹但是各文件夹里面的内容全是空的，是否与此有关？

**Comment by jianglei12138** [comment]
先确认下权限是否正常，可以比对linux或者mac上赋予相应的权限。
