### ISSUE TITLE
cups更改了什么东西？

### ISSUE THREAD

**Issue by Rachel-hsw** [jianglei12138/cups#9]
老哥，按照你的操作步骤来。成功移植到了Android系统，访问127.0.0.1：631之后，home界面正常显示。但是其他界面，打印机管理啊，任务管理啊等，全部显示NOT FOUND，会是什么原因呢？并且想向您请教一下，您的cups做了哪些更改。

**Comment by jianglei12138** [comment]
see update, sorry later....
